---
abstract: "Scans Dist::Zilla's .pm files and tries to identify classes using Class::Discover."
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::DZil: '0'
  Test::Fatal: '0'
  Test::Moose: '0'
  Test::More: '0.96'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-MetaProvides-Class
provides:
  Dist::Zilla::Plugin::MetaProvides::Class:
    file: lib/Dist/Zilla/Plugin/MetaProvides/Class.pm
    version: '2.001001'
recommends:
  Moose: '2.000'
requires:
  Class::Discover: '0'
  Dist::Zilla::MetaProvides::ProvideRecord: '2.000000'
  Dist::Zilla::Plugin::MetaProvides: '1.12044806'
  Dist::Zilla::Role::MetaProvider::Provider: '0'
  Moose: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-MetaProvides-Class/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-MetaProvides-Class
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-MetaProvides-Class.git
version: '2.001001'
